# Generated by Django 4.2.24 on 2025-10-16 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_credit_transaction_and_sale_fields'),
        ('inventory', '0030_customer_credit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_add_site_configuration_to_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_given',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Montant donné par le client en liquide', max_digits=12, null=True, verbose_name='Montant donné (FCFA)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Montant de la monnaie rendue', max_digits=12, null=True, verbose_name='Monnaie rendue (FCFA)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sarali_reference',
            field=models.CharField(blank=True, help_text='Référence de la transaction Sarali', max_length=100, null=True, verbose_name='Référence Sarali'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('mobile', 'Mobile Money'), ('transfer', 'Virement'), ('sarali', 'Sarali'), ('credit', 'Crédit')], default='cash', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Crédit'), ('payment', 'Paiement')], max_length=10, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Solde après transaction')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de transaction')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='inventory.customer', verbose_name='Client')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='sales.sale', verbose_name='Vente')),
                ('site_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='core.configuration', verbose_name='Configuration du site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction crédit',
                'verbose_name_plural': 'Transactions crédit',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
