# Generated by Django 4.2.24 on 2025-11-05 19:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_credit_transaction_and_sale_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='loyalty_discount_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Montant de la réduction en FCFA grâce aux points utilisés', max_digits=10, verbose_name='Réduction fidélité (FCFA)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='loyalty_points_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Points de fidélité gagnés lors de cette vente', max_digits=10, verbose_name='Points gagnés'),
        ),
        migrations.AddField(
            model_name='sale',
            name='loyalty_points_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Points de fidélité utilisés comme réduction', max_digits=10, verbose_name='Points utilisés'),
        ),
    ]
