# Generated by Django 4.2.24 on 2025-11-20 21:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_loyalty_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde après transaction'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_given',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant donné par le client en liquide', max_digits=12, null=True, verbose_name='Montant donné'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant de la monnaie rendue', max_digits=12, null=True, verbose_name='Monnaie rendue'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='loyalty_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant de la réduction grâce aux points utilisés', max_digits=10, verbose_name='Réduction fidélité'),
        ),
    ]
