# Generated by Django 4.2.24 on 2025-11-05 19:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0006_sale_loyalty_discount_amount_and_more'),
        ('core', '0009_credit_transaction_and_sale_fields'),
        ('inventory', '0037_customer_is_loyalty_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Exemple: 1 point pour 1000 FCFA dépensés = 1.00', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Points par montant dépensé')),
                ('amount_for_points', models.DecimalField(decimal_places=0, default=Decimal('1000'), help_text='Montant en FCFA à dépenser pour gagner le nombre de points défini', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Montant pour gagner des points (FCFA)')),
                ('amount_per_point', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Exemple: 1 point = 100 FCFA de réduction', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Valeur d'un point (FCFA)")),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver pour suspendre le programme de fidélité', verbose_name='Programme actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('site_configuration', models.OneToOneField(help_text='Site associé au programme de fidélité', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to='core.configuration', verbose_name='Configuration du site')),
            ],
            options={
                'verbose_name': 'Programme de fidélité',
                'verbose_name_plural': 'Programmes de fidélité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earned', 'Points gagnés'), ('redeemed', 'Points utilisés')], max_length=10, verbose_name='Type de transaction')),
                ('points', models.DecimalField(decimal_places=2, help_text='Nombre de points (positif pour earned, négatif pour redeemed)', max_digits=10, verbose_name='Points')),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Solde de points du client après cette transaction', max_digits=10, verbose_name='Solde après transaction')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de transaction')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='inventory.customer', verbose_name='Client')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='sales.sale', verbose_name='Vente')),
                ('site_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='core.configuration', verbose_name='Configuration du site')),
            ],
            options={
                'verbose_name': 'Transaction de fidélité',
                'verbose_name_plural': 'Transactions de fidélité',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['customer', '-transaction_date'], name='loyalty_loy_custome_cc5005_idx'), models.Index(fields=['sale'], name='loyalty_loy_sale_id_3a51ea_idx')],
            },
        ),
    ]
