# Generated by Django 4.2.24 on 2025-11-20 21:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='amount_for_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Montant à dépenser pour gagner le nombre de points défini', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant pour gagner des points'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='amount_per_point',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Exemple: 1 point = 100 de réduction', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Valeur d'un point"),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='points_per_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Exemple: 1 point pour 1000 dépensés = 1.00', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Points par montant dépensé'),
        ),
    ]
