# Generated by Django 4.2.23 on 2025-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_transaction_options_transaction_loss_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='loss_reason',
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
