# Generated by Django 4.2.13 on 2025-06-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_product_quantity_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité en stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour du stock'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
