# Generated by Django 4.2.23 on 2025-08-09 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_change_default_currency_to_fcfa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0012_brand_site_configuration_category_site_configuration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('low_stock', 'Stock faible'), ('new_products', 'Nouveaux produits')], default='manual', max_length=20, verbose_name='Source')),
                ('channel', models.CharField(choices=[('pdf', 'PDF'), ('escpos', 'Thermique (ESC/POS)')], default='pdf', max_length=20, verbose_name='Canal')),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('processing', 'En cours'), ('success', 'Succès'), ('error', 'Erreur')], default='queued', max_length=20, verbose_name='Statut')),
                ('copies_total', models.PositiveIntegerField(default=0, verbose_name='Nombre total de copies')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('site_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_batches', to='core.configuration', verbose_name='Configuration du site')),
            ],
            options={
                'verbose_name': "Lot d'étiquettes",
                'verbose_name_plural': "Lots d'étiquettes",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('type', models.CharField(choices=[('barcode', 'Code-barres'), ('qr', 'QR Code'), ('shelf', 'Étiquette rayonnage')], default='barcode', max_length=20, verbose_name='Type')),
                ('width_mm', models.PositiveIntegerField(default=40, verbose_name='Largeur (mm)')),
                ('height_mm', models.PositiveIntegerField(default=30, verbose_name='Hauteur (mm)')),
                ('dpi', models.PositiveIntegerField(default=203, verbose_name='DPI')),
                ('margins_mm', models.CharField(default='2,2,2,2', max_length=50, verbose_name='Marges (mm: top,right,bottom,left)')),
                ('layout', models.TextField(blank=True, null=True, verbose_name='Layout (HTML/Jinja ou JSON)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('site_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_templates', to='core.configuration', verbose_name='Configuration du site')),
            ],
            options={
                'verbose_name': "Modèle d'étiquette",
                'verbose_name_plural': "Modèles d'étiquettes",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_copies', models.PositiveIntegerField(default=1, verbose_name='Copies par défaut')),
                ('include_logo', models.BooleanField(default=True, verbose_name='Inclure le logo')),
                ('include_price', models.BooleanField(default=True, verbose_name='Afficher le prix')),
                ('show_cug', models.BooleanField(default=True, verbose_name='Afficher le CUG')),
                ('barcode_type', models.CharField(choices=[('EAN13', 'EAN13'), ('CODE128', 'CODE128'), ('QR', 'QR Code')], default='EAN13', max_length=20, verbose_name='Type de code')),
                ('printer_prefs', models.JSONField(blank=True, null=True, verbose_name='Préférences imprimante')),
                ('currency', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('default_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='inventory.labeltemplate', verbose_name='Modèle par défaut')),
                ('site_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_settings', to='core.configuration', verbose_name='Configuration du site')),
            ],
            options={
                'verbose_name': "Paramètres d'étiquettes",
                'verbose_name_plural': "Paramètres d'étiquettes",
            },
        ),
        migrations.CreateModel(
            name='LabelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies', models.PositiveIntegerField(default=1, verbose_name='Copies')),
                ('barcode_value', models.CharField(max_length=50, verbose_name='Valeur code')),
                ('data_snapshot', models.JSONField(blank=True, null=True, verbose_name="Données au moment de l'impression")),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.labelbatch', verbose_name='Lot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Étiquette à imprimer',
                'verbose_name_plural': 'Étiquettes à imprimer',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='labelbatch',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.labeltemplate', verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='labelbatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
