# Generated by Django 4.2.23 on 2025-08-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_labeltemplate_site_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='paper_width_mm',
            field=models.DecimalField(decimal_places=1, default=57.5, max_digits=5, verbose_name='Largeur papier (mm)'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='printing_width_mm',
            field=models.DecimalField(decimal_places=1, default=48.0, max_digits=5, verbose_name='Largeur imprimable (mm)'),
        ),
    ]
