# Generated by Django 4.2.23 on 2025-08-10 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_change_default_currency_to_fcfa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0015_labeltemplate_paper_width_mm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du catalogue')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix minimum')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix maximum')),
                ('in_stock_only', models.BooleanField(default=False, verbose_name='En stock uniquement')),
                ('include_products_without_barcode', models.BooleanField(default=True, verbose_name='Inclure produits sans code-barre')),
                ('include_products_with_barcode', models.BooleanField(default=False, verbose_name='Inclure produits avec code-barre')),
                ('cug_pattern', models.CharField(blank=True, max_length=100, verbose_name='Motif CUG (ex: PROD*)')),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('processing', 'En cours'), ('success', 'Succès'), ('failed', 'Échec')], default='queued', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('scheduled', 'Programmé'), ('api', 'API')], default='manual', max_length=20)),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='Total produits')),
                ('total_pages', models.PositiveIntegerField(default=0, verbose_name='Total pages')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin du fichier')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='Taille fichier (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('brands', models.ManyToManyField(blank=True, to='inventory.brand', verbose_name='Marques')),
                ('categories', models.ManyToManyField(blank=True, to='inventory.category', verbose_name='Catégories')),
                ('site_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.configuration', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Génération de catalogue CUG',
                'verbose_name_plural': 'Générations de catalogue CUG',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('format', models.CharField(choices=[('A4', 'A4 (210x297mm)'), ('A5', 'A5 (148x210mm)'), ('A6', 'A6 (105x148mm)'), ('custom', 'Personnalisé')], default='A4', max_length=10, verbose_name='Format')),
                ('width_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Largeur (mm)')),
                ('height_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Hauteur (mm)')),
                ('margin_top_mm', models.DecimalField(decimal_places=1, default=20.0, max_digits=4, verbose_name='Marge supérieure (mm)')),
                ('margin_bottom_mm', models.DecimalField(decimal_places=1, default=20.0, max_digits=4, verbose_name='Marge inférieure (mm)')),
                ('margin_left_mm', models.DecimalField(decimal_places=1, default=20.0, max_digits=4, verbose_name='Marge gauche (mm)')),
                ('margin_right_mm', models.DecimalField(decimal_places=1, default=20.0, max_digits=4, verbose_name='Marge droite (mm)')),
                ('header_text', models.CharField(blank=True, max_length=200, verbose_name="Texte d'en-tête")),
                ('footer_text', models.CharField(blank=True, max_length=200, verbose_name='Texte de pied de page')),
                ('show_page_numbers', models.BooleanField(default=True, verbose_name='Afficher numéros de page')),
                ('products_per_page', models.PositiveIntegerField(default=12, verbose_name='Codes-barres par page')),
                ('show_product_names', models.BooleanField(default=True, verbose_name='Afficher noms produits')),
                ('show_prices', models.BooleanField(default=True, verbose_name='Afficher prix')),
                ('show_descriptions', models.BooleanField(default=False, verbose_name='Afficher descriptions')),
                ('show_images', models.BooleanField(default=False, verbose_name='Afficher images')),
                ('barcode_type', models.CharField(choices=[('code128', 'Code 128'), ('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('code39', 'Code 39')], default='code128', max_length=20, verbose_name='Type de code-barre')),
                ('barcode_height_mm', models.DecimalField(decimal_places=1, default=15.0, max_digits=4, verbose_name='Hauteur code-barre (mm)')),
                ('include_checksum', models.BooleanField(default=True, verbose_name='Inclure checksum')),
                ('is_default', models.BooleanField(default=False, verbose_name='Modèle par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('site_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_templates', to='core.configuration', verbose_name='Configuration du site')),
            ],
            options={
                'verbose_name': 'Modèle de catalogue CUG',
                'verbose_name_plural': 'Modèles de catalogue CUG',
                'unique_together': {('site_configuration', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('page_number', models.PositiveIntegerField(default=1, verbose_name='Numéro de page')),
                ('cug_value', models.CharField(max_length=50, verbose_name='Valeur CUG')),
                ('barcode_data', models.CharField(max_length=100, verbose_name='Données code-barre')),
                ('x_position_mm', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Position X (mm)')),
                ('y_position_mm', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Position Y (mm)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.cataloggeneration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Élément de catalogue CUG',
                'verbose_name_plural': 'Éléments de catalogue CUG',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='cataloggeneration',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.catalogtemplate', verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='cataloggeneration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
