# Generated by Django 4.2.13 on 2025-08-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_barcode_unique_together_alter_barcode_ean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
