# Generated by Django 4.2.13 on 2025-08-05 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_configuration_tva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='site_web',
        ),
        migrations.AddField(
            model_name='configuration',
            name='site_name',
            field=models.CharField(blank=True, help_text='Nom unique du site/entreprise', max_length=100, null=True, unique=True, verbose_name='Nom du site'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='site_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_sites', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire du site'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_site_admin',
            field=models.BooleanField(default=False, help_text='Cet utilisateur est administrateur de son site', verbose_name='Administrateur du site'),
        ),
        migrations.AddField(
            model_name='user',
            name='site_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.configuration', verbose_name='Configuration du site'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='adresse',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='devise',
            field=models.CharField(default='€', max_length=10, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='nom_societe',
            field=models.CharField(max_length=100, verbose_name='Nom de la société'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='TVA (%)'),
        ),
    ]
