# Generated by Django 4.2.13 on 2025-08-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_make_site_fields_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='devise',
            field=models.CharField(default='FCFA', max_length=10, verbose_name='Devise'),
        ),
    ]
