# Generated by Django 4.2.23 on 2025-08-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_change_default_currency_to_fcfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Logo'),
        ),
    ]
