# Generated by Django 4.2.13 on 2025-08-26 13:06

import bolibanastock.local_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_configuration_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=bolibanastock.local_storage.LocalSiteLogoStorage(), upload_to='config/', verbose_name='Logo'),
        ),
    ]
