# Generated by Django 4.2.24 on 2025-10-16 17:17

import bolibanastock.local_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_configuration_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=bolibanastock.local_storage.LocalSiteLogoStorage(), upload_to='assets/logos/site-default/', verbose_name='Logo'),
        ),
    ]
