# Generated by Django 4.2.24 on 2025-11-13 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_credit_transaction_and_sale_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code à 6 chiffres pour la réinitialisation', max_length=6, verbose_name='Code OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('used', models.BooleanField(default=False, help_text='Indique si le code a déjà été utilisé', verbose_name='Utilisé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Token de réinitialisation',
                'verbose_name_plural': 'Tokens de réinitialisation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'code', 'used'], name='core_passwo_user_id_2b1b58_idx'), models.Index(fields=['expires_at'], name='core_passwo_expires_71ae22_idx')],
            },
        ),
    ]
