# Generated by Django 4.2.24 on 2025-11-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='devise',
            field=models.CharField(choices=[('FCFA', 'Franc CFA (FCFA)'), ('XOF', 'Franc CFA Ouest (XOF)'), ('XAF', 'Franc CFA Centre (XAF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dollar US (USD)'), ('GBP', 'Livre Sterling (GBP)'), ('JPY', 'Yen Japonais (JPY)'), ('CNY', 'Yuan Chinois (CNY)'), ('INR', 'Roupie Indienne (INR)'), ('BRL', 'Real Brésilien (BRL)'), ('ZAR', 'Rand Sud-Africain (ZAR)'), ('NGN', 'Naira Nigérian (NGN)'), ('GHS', 'Cedi Ghanéen (GHS)'), ('KES', 'Shilling Kenyan (KES)'), ('EGP', 'Livre Égyptienne (EGP)'), ('MAD', 'Dirham Marocain (MAD)'), ('TND', 'Dinar Tunisien (TND)'), ('DZD', 'Dinar Algérien (DZD)'), ('XPF', 'Franc Pacifique (XPF)'), ('MGA', 'Ariary Malgache (MGA)')], default='FCFA', max_length=10, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='est_actif',
            field=models.BooleanField(default=True, help_text='Désactivez ceci plutôt que de supprimer le compte', verbose_name='Est actif'),
        ),
    ]
