# Generated by Django 4.2.24 on 2025-11-29 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_create_initial_plans'),
        ('core', '0011_alter_configuration_devise_alter_user_est_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text="Plan d'abonnement actif pour ce site", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='subscription.plan', verbose_name="Plan d'abonnement"),
        ),
    ]
