# Generated by Django 4.2.23 on 2025-06-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20250614_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=50, verbose_name='Code-barres')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Code-barres principal')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Code-barres',
                'verbose_name_plural': 'Codes-barres',
                'ordering': ['-is_primary', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Validée'), ('cancelled', 'Annulée')], default='pending', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.RenameModel(
            old_name='Marque',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Fournisseur',
            new_name='Supplier',
        ),
        migrations.AlterUniqueTogether(
            name='codebarres',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='codebarres',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='client',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='produit',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seuil_alerte',
            new_name='alert_threshold',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='marque',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantite',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_modification',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='seuil_alerte',
            new_name='alert_threshold',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='produit',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='quantite',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='date_modification',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='adresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='produit',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='quantite',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date_transaction',
            new_name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type_transaction',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('transfer', 'Transfert')], default='in', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
