# Generated by Django 4.2.23 on 2025-06-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleitem_options_remove_sale_client_and_more'),
        ('inventory', '0007_remove_product_price_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='loss_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif de la casse'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='cug',
            field=models.CharField(max_length=50, unique=True, verbose_name='CUG'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('in', 'Achat'), ('out', 'Vente'), ('loss', 'Casse')], default='in', max_length=10),
        ),
    ]
