# Generated by Django 4.2.23 on 2025-08-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_make_site_fields_required'),
        ('inventory', '0011_product_quantity_product_stock_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='site_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='core.configuration', verbose_name='Configuration du site'),
        ),
        migrations.AddField(
            model_name='category',
            name='site_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.configuration', verbose_name='Configuration du site'),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.configuration', verbose_name='Configuration du site'),
        ),
        migrations.AddField(
            model_name='order',
            name='site_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.configuration', verbose_name='Configuration du site'),
        ),
        migrations.AddField(
            model_name='product',
            name='site_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.configuration', verbose_name='Configuration du site'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='site_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.configuration', verbose_name='Configuration du site'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='site_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.configuration', verbose_name='Configuration du site'),
        ),
    ]
