# Generated by Django 4.2.23 on 2025-08-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_change_default_currency_to_fcfa'),
        ('inventory', '0013_labelbatch_labeltemplate_labelsetting_labelitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltemplate',
            name='site_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_templates', to='core.configuration', verbose_name='Configuration du site'),
        ),
    ]
