# Generated by Django 4.2.13 on 2025-08-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_add_barcode_field_to_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barcode',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='ean',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code-barres'),
        ),
    ]
