# Generated by Django 4.2.13 on 2025-08-26 13:06

import bolibanastock.local_storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_configuration_logo'),
        ('inventory', '0020_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=bolibanastock.local_storage.LocalProductImageStorage(), upload_to='products/', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='ProductCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copied_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de copie')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Dernière synchronisation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Copie active')),
                ('sync_prices', models.BooleanField(default=True, verbose_name='Synchroniser les prix')),
                ('sync_stock', models.BooleanField(default=False, verbose_name='Synchroniser le stock')),
                ('sync_images', models.BooleanField(default=True, verbose_name='Synchroniser les images')),
                ('sync_description', models.BooleanField(default=True, verbose_name='Synchroniser la description')),
                ('copied_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_products', to='inventory.product', verbose_name='Produit copié')),
                ('destination_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_copied', to='core.configuration', verbose_name='Site destination')),
                ('original_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='inventory.product', verbose_name='Produit original')),
                ('source_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_shared', to='core.configuration', verbose_name='Site source')),
            ],
            options={
                'verbose_name': 'Copie de produit',
                'verbose_name_plural': 'Copies de produits',
                'ordering': ['-copied_at'],
                'unique_together': {('original_product', 'destination_site')},
            },
        ),
    ]
