# Generated by Django 4.2.13 on 2025-08-31 08:02

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_product_image_productcopy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.inventory.models.get_brand_logo_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.inventory.models.get_category_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.inventory.models.get_product_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité en stock'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('in', 'Achat'), ('out', 'Vente'), ('loss', 'Casse'), ('backorder', 'Backorder'), ('adjustment', 'Ajustement')], default='in', max_length=10),
        ),
    ]
