# Generated by Django 4.2.13 on 2025-09-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_fix_transaction_quantity_unsigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='generated_ean',
            field=models.CharField(blank=True, help_text='EAN-13 généré automatiquement depuis le CUG', max_length=13, null=True, verbose_name='EAN Généré'),
        ),
    ]
