# Generated by Django 4.2.13 on 2025-09-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_add_generated_ean_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Cette catégorie est accessible à tous les sites', verbose_name='Catégorie globale'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_rayon',
            field=models.BooleanField(default=False, help_text='Cette catégorie représente un rayon de supermarché standardisé', verbose_name='Rayon de supermarché'),
        ),
        migrations.AddField(
            model_name='category',
            name='rayon_type',
            field=models.CharField(blank=True, choices=[('frais_libre_service', 'Frais Libre Service'), ('rayons_traditionnels', 'Rayons Traditionnels'), ('epicerie', 'Épicerie'), ('petit_dejeuner', 'Petit-déjeuner'), ('tout_pour_bebe', 'Tout pour bébé'), ('liquides', 'Liquides'), ('non_alimentaire', 'Non Alimentaire'), ('dph', 'DPH (Droguerie, Parfumerie, Hygiène)'), ('textile', 'Textile'), ('bazar', 'Bazar')], help_text='Type de rayon de supermarché (uniquement si is_rayon=True)', max_length=50, null=True, verbose_name='Type de rayon'),
        ),
    ]
