# Generated by Django 4.2.23 on 2025-09-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_global_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rayon_type',
            field=models.CharField(blank=True, choices=[('frais_libre_service', 'Frais Libre Service'), ('rayons_traditionnels', 'Rayons Traditionnels'), ('epicerie', 'Épicerie'), ('petit_dejeuner', 'Petit-déjeuner'), ('tout_pour_bebe', 'Tout pour bébé'), ('liquides', 'Liquides'), ('non_alimentaire', 'Non Alimentaire'), ('dph', 'DPH (Droguerie, Parfumerie, Hygiène)'), ('textile', 'Textile'), ('bazar', 'Bazar'), ('sante_pharmacie', 'Santé et Pharmacie, Parapharmacie'), ('jardinage', 'Jardinage'), ('high_tech', 'High-tech, Téléphonie'), ('jouets_livres', 'Jouets, Jeux Vidéo, Livres'), ('meubles_linge', 'Meubles, Linge de Maison'), ('animalerie', 'Animalerie'), ('mode_bijoux', 'Mode, Bijoux, Bagagerie')], help_text='Type de rayon de supermarché (uniquement si is_rayon=True)', max_length=50, null=True, verbose_name='Type de rayon'),
        ),
    ]
