# Generated by Django 4.2.24 on 2025-09-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_add_new_rayon_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='rayons',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez les rayons où cette marque est présente', limit_choices_to={'is_active': True, 'is_rayon': True}, related_name='brands', to='inventory.category', verbose_name='Rayons associés'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rayon_type',
            field=models.CharField(blank=True, choices=[('frais_libre_service', 'Frais Libre Service'), ('rayons_traditionnels', 'Rayons Traditionnels'), ('epicerie', 'Épicerie'), ('tout_pour_bebe', 'Tout pour bébé'), ('liquides', 'Liquides, Boissons'), ('non_alimentaire', 'Non Alimentaire'), ('dph', 'DPH (Droguerie, Parfumerie, Hygiène)'), ('textile', 'Textile'), ('bazar', 'Bazar'), ('sante_pharmacie', 'Santé et Pharmacie, Parapharmacie'), ('jardinage', 'Jardinage'), ('high_tech', 'High-tech, Téléphonie'), ('jouets_livres', 'Jouets, Jeux Vidéo, Livres'), ('meubles_linge', 'Meubles, Linge de Maison'), ('animalerie', 'Animalerie'), ('mode_bijoux', 'Mode, Bijoux, Bagagerie')], help_text='Type de rayon de supermarché (uniquement si is_rayon=True)', max_length=50, null=True, verbose_name='Type de rayon'),
        ),
    ]
