# Generated by Django 4.2.24 on 2025-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20251015_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='ean',
            field=models.CharField(max_length=50, verbose_name='Code-barres'),
        ),
    ]
