# Generated by Django 4.2.24 on 2025-10-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_barcode_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_balance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Montant total du crédit en cours (négatif = dette)', max_digits=12, verbose_name='Solde crédit (FCFA)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Limite de crédit autorisée (optionnel)', max_digits=12, null=True, verbose_name='Limite de crédit (FCFA)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Désactiver pour empêcher les nouvelles ventes à crédit', verbose_name='Client actif'),
        ),
    ]
