# Generated by Django 4.2.24 on 2025-10-17 06:15

from django.db import migrations
from django.conf import settings


def cleanup_orphaned_catalog_generations(apps, schema_editor):
    """
    Supprime les CatalogGeneration qui référencent des utilisateurs inexistants
    dans la table core_user
    """
    CatalogGeneration = apps.get_model('inventory', 'CatalogGeneration')
    User = apps.get_model('core', 'User')
    
    # Récupérer tous les IDs d'utilisateurs valides dans core_user
    valid_user_ids = set(User.objects.values_list('id', flat=True))
    
    # Trouver les CatalogGeneration avec des user_id invalides
    orphaned_generations = CatalogGeneration.objects.exclude(user_id__in=valid_user_ids)
    
    count = orphaned_generations.count()
    if count > 0:
        print(f"🧹 Suppression de {count} générations de catalogue orphelines...")
        orphaned_generations.delete()
        print(f"✅ {count} générations orphelines supprimées")
    else:
        print("✅ Aucune génération de catalogue orpheline trouvée")


def reverse_cleanup(apps, schema_editor):
    """
    Opération inverse - ne peut pas être annulée car les données sont supprimées
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_customer_credit_fields'),
        ('core', '0006_change_default_currency_to_fcfa'),
    ]

    operations = [
        migrations.RunPython(
            cleanup_orphaned_catalog_generations,
            reverse_cleanup,
        ),
    ]
