# Generated by Django 4.2.24 on 2025-10-17 06:32

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def fix_catalog_user_foreign_key(apps, schema_editor):
    """
    Force la correction de la contrainte de clé étrangère pour CatalogGeneration.user
    en supprimant et recréant le champ avec la bonne référence
    """
    CatalogGeneration = apps.get_model('inventory', 'CatalogGeneration')
    
    # Supprimer toutes les CatalogGeneration orphelines
    from apps.core.models import User as CoreUser
    valid_user_ids = set(CoreUser.objects.values_list('id', flat=True))
    orphaned = CatalogGeneration.objects.exclude(user_id__in=valid_user_ids)
    
    count = orphaned.count()
    if count > 0:
        print(f"🧹 Suppression de {count} générations orphelines avant correction FK...")
        orphaned.delete()
        print(f"✅ {count} générations orphelines supprimées")
    
    print("✅ Contrainte de clé étrangère corrigée pour CatalogGeneration.user")


def reverse_fix(apps, schema_editor):
    """
    Opération inverse - ne peut pas être annulée
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_cleanup_orphaned_catalog_generations'),
        ('core', '0006_change_default_currency_to_fcfa'),
    ]

    operations = [
        # D'abord, supprimer toutes les CatalogGeneration orphelines
        migrations.RunPython(
            fix_catalog_user_foreign_key,
            reverse_fix,
        ),
        # Supprimer le champ user existant
        migrations.RemoveField(
            model_name='cataloggeneration',
            name='user',
        ),
        # Recréer le champ user avec la bonne référence
        migrations.AddField(
            model_name='cataloggeneration',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                to=settings.AUTH_USER_MODEL, 
                verbose_name='Utilisateur'
            ),
        ),
    ]
