# Generated by Django 4.2.24 on 2025-10-17 06:32

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def fix_catalog_user_foreign_key(apps, schema_editor):
    """
    Force la correction de la contrainte de clé étrangère pour CatalogGeneration.user
    en supprimant et recréant le champ avec la bonne référence
    """
    CatalogGeneration = apps.get_model('inventory', 'CatalogGeneration')
    
    # Supprimer toutes les CatalogGeneration avec user_id NULL ou orphelines
    from apps.core.models import User as CoreUser
    valid_user_ids = set(CoreUser.objects.values_list('id', flat=True))
    
    # Supprimer les CatalogGeneration avec user_id NULL
    null_user_count = CatalogGeneration.objects.filter(user_id__isnull=True).count()
    if null_user_count > 0:
        print(f"🧹 Suppression de {null_user_count} générations avec user_id NULL...")
        CatalogGeneration.objects.filter(user_id__isnull=True).delete()
        print(f"✅ {null_user_count} générations avec user_id NULL supprimées")
    
    # Supprimer les CatalogGeneration orphelines (user_id invalide)
    orphaned = CatalogGeneration.objects.exclude(user_id__in=valid_user_ids)
    count = orphaned.count()
    if count > 0:
        print(f"🧹 Suppression de {count} générations orphelines avant correction FK...")
        orphaned.delete()
        print(f"✅ {count} générations orphelines supprimées")
    
    print("✅ Contrainte de clé étrangère corrigée pour CatalogGeneration.user")


def cleanup_null_users(apps, schema_editor):
    """
    Supprimer toutes les CatalogGeneration avec user_id NULL après la recréation du champ
    """
    CatalogGeneration = apps.get_model('inventory', 'CatalogGeneration')
    
    # Supprimer les CatalogGeneration avec user_id NULL
    null_user_count = CatalogGeneration.objects.filter(user_id__isnull=True).count()
    if null_user_count > 0:
        print(f"🧹 Suppression de {null_user_count} générations avec user_id NULL après recréation du champ...")
        CatalogGeneration.objects.filter(user_id__isnull=True).delete()
        print(f"✅ {null_user_count} générations avec user_id NULL supprimées")
    


def reverse_fix(apps, schema_editor):
    """
    Opération inverse - ne peut pas être annulée
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_cleanup_orphaned_catalog_generations'),
        ('core', '0006_change_default_currency_to_fcfa'),
    ]

    operations = [
        # D'abord, supprimer toutes les CatalogGeneration orphelines et avec user_id NULL
        migrations.RunPython(
            fix_catalog_user_foreign_key,
            reverse_fix,
        ),
        # Supprimer le champ user existant
        migrations.RemoveField(
            model_name='cataloggeneration',
            name='user',
        ),
        # Recréer le champ user avec la bonne référence (nullable=True temporairement)
        migrations.AddField(
            model_name='cataloggeneration',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                to=settings.AUTH_USER_MODEL, 
                verbose_name='Utilisateur',
                null=True,  # Temporairement nullable pour éviter l'erreur
            ),
        ),
        # Supprimer les valeurs NULL restantes après la recréation du champ
        migrations.RunPython(
            cleanup_null_users,
            reverse_fix,
        ),
        # Rendre le champ non-nullable avec SQL brut pour éviter les problèmes de trigger
        migrations.RunSQL(
            # SQL pour rendre la colonne NOT NULL
            sql="""
                ALTER TABLE inventory_cataloggeneration 
                ALTER COLUMN user_id SET NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE inventory_cataloggeneration 
                ALTER COLUMN user_id DROP NOT NULL;
            """,
        ),
    ]
