# Generated by Django 4.2.24 on 2025-10-17 06:45

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_fix_catalog_user_foreign_key'),
        ('core', '0006_change_default_currency_to_fcfa'),
    ]

    operations = [
        # Supprimer complètement la table CatalogGeneration
        migrations.DeleteModel(
            name='CatalogGeneration',
        ),
        # Supprimer aussi CatalogItem qui dépend de CatalogGeneration
        migrations.DeleteModel(
            name='CatalogItem',
        ),
        # Recréer CatalogGeneration avec la bonne structure
        migrations.CreateModel(
            name='CatalogGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du catalogue')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix minimum')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix maximum')),
                ('in_stock_only', models.BooleanField(default=False, verbose_name='En stock uniquement')),
                ('include_products_without_barcode', models.BooleanField(default=True, verbose_name='Inclure produits sans code-barre')),
                ('include_products_with_barcode', models.BooleanField(default=False, verbose_name='Inclure produits avec code-barre')),
                ('cug_pattern', models.CharField(blank=True, max_length=100, verbose_name='Motif CUG (ex: PROD*)')),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('processing', 'En cours'), ('success', 'Succès'), ('failed', 'Échec')], default='queued', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('scheduled', 'Programmé'), ('api', 'API')], default='manual', max_length=20)),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='Total produits')),
                ('total_pages', models.PositiveIntegerField(default=0, verbose_name='Total pages')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin du fichier')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='Taille fichier (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('error_message', models.TextField(blank=True, verbose_name='Message d\'erreur')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.catalogtemplate', verbose_name='Modèle')),
                ('site_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.configuration', verbose_name='Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Génération de catalogue CUG',
                'verbose_name_plural': 'Générations de catalogue CUG',
                'ordering': ['-created_at'],
            },
        ),
        # Recréer CatalogItem
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('page_number', models.PositiveIntegerField(default=1, verbose_name='Numéro de page')),
                ('cug_value', models.CharField(max_length=50, verbose_name='Valeur CUG')),
                ('barcode_data', models.CharField(max_length=100, verbose_name='Données code-barre')),
                ('x_position_mm', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Position X (mm)')),
                ('y_position_mm', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Position Y (mm)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.cataloggeneration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Élément de catalogue CUG',
                'verbose_name_plural': 'Éléments de catalogue CUG',
                'ordering': ['position'],
            },
        ),
    ]
