# Generated by Django 4.2.24 on 2025-10-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_force_recreate_catalog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloggeneration',
            name='brands',
            field=models.ManyToManyField(blank=True, to='inventory.brand', verbose_name='Marques'),
        ),
        migrations.AddField(
            model_name='cataloggeneration',
            name='categories',
            field=models.ManyToManyField(blank=True, to='inventory.category', verbose_name='Catégories'),
        ),
    ]
