# Generated by Django 4.2.24 on 2025-11-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_fix_catalog_user_null_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelbatch',
            name='channel',
            field=models.CharField(choices=[('pdf', 'PDF'), ('escpos', 'Thermique (ESC/POS)'), ('tsc', 'Thermique (TSC)')], default='pdf', max_length=20, verbose_name='Canal'),
        ),
    ]
