# Generated by Django 4.2.24 on 2025-11-05 19:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_labelbatch_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_loyalty_member',
            field=models.BooleanField(default=False, help_text='Indique si le client est inscrit au programme de fidélité', verbose_name='Membre du programme de fidélité'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_joined_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle le client s'est inscrit au programme", null=True, verbose_name="Date d'inscription à la fidélité"),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solde de points de fidélité du client', max_digits=10, verbose_name='Points de fidélité'),
        ),
    ]
