# Generated by Django 4.2.24 on 2025-11-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_customer_is_loyalty_member_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False)), fields=('phone', 'site_configuration'), name='unique_phone_per_site', violation_error_message='Un client avec ce numéro de téléphone existe déjà pour ce site.'),
        ),
    ]
