# Generated by Django 4.2.24 on 2025-11-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_add_unique_phone_per_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total du crédit en cours (négatif = dette)', max_digits=12, verbose_name='Solde crédit'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limite de crédit autorisée (optionnel)', max_digits=12, null=True, verbose_name='Limite de crédit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
