# Generated by Django 4.2.24 on 2025-11-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_alter_customer_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_unit_type',
            field=models.CharField(choices=[('quantity', 'Quantité'), ('weight', 'Poids')], default='quantity', help_text='Définit si le produit est vendu par quantité (unité) ou par poids (kg/g)', max_length=10, verbose_name='Type de vente'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogramme'), ('g', 'Gramme')], help_text='Unité de poids (kg ou g) - requis uniquement pour les produits au poids', max_length=2, null=True, verbose_name='Unité de poids'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='alert_threshold',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=10, verbose_name="Seuil d'alerte"),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantité en stock'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
