# Generated by Django 4.2.23 on 2025-06-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
