# Generated by Django 4.2.23 on 2025-06-15 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_barcode_customer_order_orderitem_rename_marque_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_payment_sale_saleitem_remove_paiement_vente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Article vendu', 'verbose_name_plural': 'Articles vendus'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='client',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.customer', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('mobile', 'Mobile Money'), ('transfer', 'Virement')], default='cash', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence paiement'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('partial', 'Partiel'), ('paid', 'Payé')], default='pending', max_length=20, verbose_name='Statut du paiement'),
        ),
        migrations.AddField(
            model_name='sale',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sous-total'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant TVA'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de TVA (%)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de vente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendeur'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire'),
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Montant d'ouverture")),
                ('closing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant de fermeture')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée')], default='open', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'ordering': ['-opening_date'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.cashregister', verbose_name='Caisse'),
        ),
    ]
