# Generated by Django 4.2.13 on 2025-08-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_change_default_currency_to_fcfa'),
        ('sales', '0003_alter_saleitem_options_remove_sale_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='site_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.configuration', verbose_name='Configuration du site'),
        ),
    ]
