# Generated by Django 4.2.24 on 2025-11-29 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom affiché du plan (ex: Starter, Professional)', max_length=100, verbose_name='Nom du plan')),
                ('slug', models.SlugField(help_text='Identifiant unique du plan (ex: starter, professional)', unique=True, verbose_name='Slug')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix mensuel en euros', max_digits=10, verbose_name='Prix mensuel (€)')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix annuel en euros (réduction de 20% appliquée)', max_digits=10, verbose_name='Prix annuel (€)')),
                ('max_sites', models.IntegerField(default=1, help_text='Nombre maximum de sites/points de vente autorisés', verbose_name='Nombre maximum de sites')),
                ('max_products', models.IntegerField(blank=True, help_text='Nombre maximum de produits (null = illimité)', null=True, verbose_name='Nombre maximum de produits')),
                ('max_users', models.IntegerField(default=1, help_text="Nombre maximum d'utilisateurs autorisés", verbose_name="Nombre maximum d'utilisateurs")),
                ('max_transactions_per_month', models.IntegerField(blank=True, help_text='Nombre maximum de transactions par mois (null = illimité)', null=True, verbose_name='Transactions maximum par mois')),
                ('has_loyalty_program', models.BooleanField(default=False, help_text='Accès au programme de fidélité', verbose_name='Programme de fidélité')),
                ('has_advanced_reports', models.BooleanField(default=False, help_text='Accès aux rapports avancés et analyses', verbose_name='Rapports avancés')),
                ('has_api_access', models.BooleanField(default=False, help_text="Accès à l'API d'intégration", verbose_name='Accès API')),
                ('has_priority_support', models.BooleanField(default=False, help_text='Support prioritaire (email + chat)', verbose_name='Support prioritaire')),
                ('history_months', models.IntegerField(default=6, help_text="Nombre de mois d'historique conservé", verbose_name='Historique (mois)')),
                ('is_active', models.BooleanField(default=True, help_text='Plan disponible pour souscription', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='UsageLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(default=0, help_text='Nombre total de produits créés par cet utilisateur', verbose_name='Nombre de produits')),
                ('transaction_count_this_month', models.IntegerField(default=0, help_text='Nombre de transactions effectuées ce mois', verbose_name='Transactions ce mois')),
                ('last_transaction_reset', models.DateField(default=django.utils.timezone.now, help_text='Date de la dernière réinitialisation du compteur mensuel', verbose_name='Dernière réinitialisation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_limit', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Limite d'utilisation",
                'verbose_name_plural': "Limites d'utilisation",
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Annulée'), ('past_due', 'En retard'), ('trialing', 'Essai'), ('expired', 'Expirée')], default='trialing', max_length=20, verbose_name='Statut')),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début de période')),
                ('current_period_end', models.DateTimeField(verbose_name='Fin de période')),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text="L'abonnement sera annulé à la fin de la période actuelle", verbose_name='Annuler à la fin de période')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.plan', verbose_name='Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='FCFA', help_text='Devise du paiement (FCFA, EUR, etc.)', max_length=10, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(choices=[('manual', 'Manuel'), ('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('cash', 'Espèces'), ('other', 'Autre')], default='manual', max_length=20, verbose_name='Méthode de paiement')),
                ('payment_reference', models.CharField(blank=True, help_text='Numéro de transaction, référence virement, etc.', max_length=100, null=True, verbose_name='Référence de paiement')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur le paiement', null=True, verbose_name='Notes')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscription.subscription', verbose_name='Abonnement')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payments', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
            },
        ),
    ]
