# Generated by Django 4.2.24 on 2025-11-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['name'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price_monthly',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price_yearly',
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('FCFA', 'Franc CFA (FCFA)'), ('XOF', 'Franc CFA Ouest (XOF)'), ('XAF', 'Franc CFA Centre (XAF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dollar US (USD)'), ('GBP', 'Livre Sterling (GBP)'), ('JPY', 'Yen Japonais (JPY)'), ('CNY', 'Yuan Chinois (CNY)'), ('INR', 'Roupie Indienne (INR)'), ('BRL', 'Real Brésilien (BRL)'), ('ZAR', 'Rand Sud-Africain (ZAR)'), ('NGN', 'Naira Nigérian (NGN)'), ('GHS', 'Cedi Ghanéen (GHS)'), ('KES', 'Shilling Kenyan (KES)'), ('EGP', 'Livre Égyptienne (EGP)'), ('MAD', 'Dirham Marocain (MAD)'), ('TND', 'Dinar Tunisien (TND)'), ('DZD', 'Dinar Algérien (DZD)'), ('XPF', 'Franc Pacifique (XPF)'), ('MGA', 'Ariary Malgache (MGA)')], help_text='Devise pour ce prix', max_length=10, verbose_name='Devise')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix mensuel dans cette devise', max_digits=10, verbose_name='Prix mensuel')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix annuel dans cette devise (réduction de 20% appliquée)', max_digits=10, verbose_name='Prix annuel')),
                ('is_active', models.BooleanField(default=True, help_text='Ce prix est-il actif pour cette devise?', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='subscription.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Prix de plan',
                'verbose_name_plural': 'Prix de plans',
                'ordering': ['plan', 'currency'],
                'unique_together': {('plan', 'currency')},
            },
        ),
    ]
