# Generated by Django 4.2.24 on 2025-11-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_configuration_subscription_plan'),
        ('subscription', '0002_create_initial_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usagelimit',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='site',
            field=models.OneToOneField(blank=True, help_text='Site/Configuration qui possède cet abonnement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.configuration', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='usagelimit',
            name='site',
            field=models.OneToOneField(blank=True, help_text="Site/Configuration dont on suit l'utilisation", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_limit', to='core.configuration', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(help_text='Abonnement du site', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscription.subscription', verbose_name='Abonnement'),
        ),
        migrations.AlterField(
            model_name='usagelimit',
            name='product_count',
            field=models.IntegerField(default=0, help_text='Nombre total de produits créés sur ce site', verbose_name='Nombre de produits'),
        ),
        migrations.AlterField(
            model_name='usagelimit',
            name='transaction_count_this_month',
            field=models.IntegerField(default=0, help_text='Nombre de transactions effectuées ce mois sur ce site', verbose_name='Transactions ce mois'),
        ),
    ]
