# Generated by Django 4.2.24 on 2025-11-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_make_site_fields_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='period',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', help_text='Période de facturation : mensuel ou annuel', max_length=10, verbose_name='Période'),
        ),
    ]
