# Generated by Django 4.2.24 on 2025-11-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscription_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='period',
            new_name='billing_period',
        ),
    ]
