# Generated by Django 4.2.24 on 2025-11-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_rename_period_to_billing_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='billing_period',
        ),
        migrations.AddField(
            model_name='payment',
            name='period',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', help_text='Période couverte par ce paiement : mensuel (30 jours) ou annuel (365 jours)', max_length=10, verbose_name="Type d'abonnement"),
        ),
    ]
